futebolsite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('staticpages.urls')),
    path('times/', include('times.urls')),
    path('admin/', admin.site.urls),
]

staticpages/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('about/', views.about, name='about'), 
    path('', views.index, name='index'),
]

times/urls.py
from django.urls import path
from . import views

app_name = 'times'
urlpatterns = [
    path('', views.PostsListView.as_view(), name='index'),
    path('search/', views.search_posts, name='search'),
    path('create/', views.PostsCreateView.as_view(), name='create'),
    path('<int:pk>/', views.PostsDetailView.as_view(), name='detail'),
    path('update/<int:pk>/', views.PostsUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', views.PostsDeleteView.as_view(), name='delete'),
    path('<int:post_id>/comment/', views.create_comment, name='comment'),
    path('categories/', views.CategoriesListView.as_view(), name='categories'),
    path('categories/<int:category_id>/', views.categories_detail_list, name='categoriesdetail'),



]

staticpages/models.py
from django.db import models

# Create your models here.

times/models.py
from django.db import models
from django.conf import settings


class Posts(models.Model):
    nome = models.CharField(max_length=1000)
    data = models.IntegerField()
    text = models.CharField(max_length=1000)
    image_url = models.URLField(max_length=200, null=True)

    def __str__(self):
        return f'{self.nome} ({self.data})'

class Comentarios(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    text = models.CharField(max_length=255)
    data = models.DateTimeField(auto_now=True)
    post = models.ForeignKey(Posts, on_delete=models.CASCADE)

    def __str__(self):
        return f'"{self.text}" - {self.author.username}'

class Categorias(models.Model):
    nome = models.CharField(max_length=255)
    descri = models.CharField(max_length=255)
    posts = models.ManyToManyField(Posts)

    def __str__(self):
        return f'{self.nome}'

times/forms.py
from django.forms import ModelForm
from .models import Posts, Comentarios


class PostsForm(ModelForm):
        class Meta:
            model = Posts
            fields = [
                'nome',
                'data',
                'text',
                'image_url',
            ]
            labels = {
                'nome': 'Título',
                'data': 'Ano de Publicação',
                'text': 'Conteudo',
                'image_url': 'URL da Imagem',
        }

class CommentsForm(ModelForm):
        class Meta:
            model = Comentarios
            fields = [
                'author',
                'text',
            ]
            labels = {
                'author': 'Usuário',
                'text': 'Conteudo do comentario',
        }

staticpages/views.py
from django.shortcuts import render


def index(request):
    context = {}
    return render(request, 'staticpages/index.html', context)


def about(request):
    context = {}
    return render(request, 'staticpages/about.html', context)

times/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from .models import Posts, Comentarios, Categorias
from django.shortcuts import render, get_object_or_404
from .forms import PostsForm, CommentsForm
from django.views import generic

class PostsDetailView(generic.DetailView):
    model = Posts
    context_object_name = 'post'
    template_name = 'times/detail.html'

class PostsListView(generic.ListView):
    model = Posts
    context_object_name = 'list_post'
    template_name = 'times/index.html'

def search_posts(request):
    context = {}
    if request.GET.get('query', False):
        search_term = request.GET['query'].lower()
        list_post = Posts.objects.filter(nome__icontains=search_term)
        context = {"list_post": list_post}
    return render(request, 'times/search.html', context)

class PostsCreateView(generic.CreateView):
    def get(self, request, *args, **kwargs):
        context = {'form': PostsForm()}
        return render(request, 'times/create.html', context)

    def post(self, request, *args, **kwargs):
        form = PostsForm(request.POST)
        if form.is_valid():
            post = form.save()
            post.save()
            return HttpResponseRedirect(reverse('times:detail', args=[post.id]))
        return render(request, 'times/create.html', {'form': form})

class PostsUpdateView(generic.UpdateView):
    context_object_name = 'post'
    form_class = PostsForm
    model = Posts
    template_class = PostsForm
    template_name = "times/update.html"

    def get_success_url(self):
        return reverse('times:detail', kwargs={'pk': self.object.id})

class PostsDeleteView(generic.DeleteView):
    model = Posts
    context_object_name = 'post'
    template_name = 'times/delete.html'
    def get_success_url(self):
        return reverse('times:index')

def create_comment(request, post_id):
    post = get_object_or_404(Posts, pk=post_id)
    if request.method == 'POST':
        form = CommentsForm(request.POST)
        if form.is_valid():
            comment_author = form.cleaned_data['author']
            comment_text = form.cleaned_data['text']
            comment = Comentarios(author=comment_author,
                            text=comment_text,
                            post=post)
            comment.save()
            return HttpResponseRedirect(
                reverse('times:detail', args=(post_id, )))
    else:
        form = CommentsForm()
    context = {'form': form, 'post': post}
    return render(request, 'times/comment.html', context)

class CategoriesListView(generic.ListView):
    model = Categorias
    template_name = 'times/categories.html'

def categories_detail_list(request, category_id):
    category = get_object_or_404(Categorias, pk = category_id)
    context = {'category' : category}
    return render(request, 'times/categoriesdetail.html', context)

staticpages/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}{% endblock %} BSB | Não acredite nas mentiras dele
    </title>
    <link href="https://fonts.googleapis.com/css?family=Inter&display=swap" rel="stylesheet" />
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}"> 
</head>

<body>
    <header id="cabecalho-principal">
        <a href="{% url 'index' %}"></a><img src="{% static 'cbf.png' %}" width="124" height="124">
        <h1>BLOG DA SELEÇÃO BRASILEIRA</h1>
    </header>

    
<nav id="navegacao-principal">
    <ul>
        <li><a href="{% url 'index' %}">Pagina Inicial</a></li>
        <li><a href="{% url 'about' %}">Sobre o site</a></li>
        <li><a href="{% url 'times:index' %}">Publicações</a></li>
        <li><a href="{% url 'times:categories' %}">Categorias</a></li>
        <li><a href="{% url 'times:create' %}">Adicionar nova publicação</a></li>
    </ul>
</nav>

    <main id="conteiner-principal">
        {% block content %}
        {% endblock content %}
    </main>
    <footer id="rodape-principal">
        <p>Confederação Brasileira de Futebol. </p>
        <p>Todos os direitos reservados. 2021 </p>
    </footer>
</body>

</html>

staticpages/templates/staticpages/about.html
{% extends 'base.html' %}

{% load static %}

{% block title %}
Sobre o site
{% endblock title %}

{% block content %}
<div class = 'p2'>
Sobre este site
</div>

<div class = 'branco'>
Este site foi um projeto da diciplina PMR3304 - Sistemas de Informação da Escola Politecnica da Universidade de São Paulo.
</div>

<img src="{% static 'poli.jpg' %}" width = "500" >

{% endblock content %}

staticpages/templates/staticpages/index.html
{% extends 'base.html' %}

{% load static %}

{% block title %}
Pagina Inicial
{% endblock title %}

{% block content %}
<article>
    <div class = 'branco'>
    Bem vindos ao maior e melhor blog não oficial sobre a seleção brasilera. Esse é um espaço feito de torcedores fanáticos 
    para torcedores, onde se encontram desde aqueles que acompanham
    a seleção em seus tempos aureos, até aqueles que seguem a apoiar a amarelinha nos dias de hoje.
</div>
</article>
<section>
    <h2>Nesse site você vai conseguir: </h2> <h4>-Encontrar as principais noticias da seleção;</h4>
    <h4>-Ver opiniões de torcedores que realmente se importam com o rumo da seleção;</h4> 
    <h4>-Criar seu proprio post, dando sua opínião, ou contando aquela noticia quentinha que só voce sabe;</h4> 
    <h4>-Comentar e interagir com outros torcedores.</h4> 
</section>
<article>
    <div class = 'p2'>
        E não se esqueçam 
        <img src="{% static 'vai.png' %}" width = "300" >
    </div>
</article>
{% endblock content %}

times/templates/times/categories.html
{% extends 'base.html' %}

{% load static %}

{% block title %}
Categorias
{% endblock title %}

{% block content %}
<div class = 'p2'>
Lista de Categorias
</div>
<div class = 'branco'>
    {% for categorias in categorias_list %}

            <a href="{% url 'times:categoriesdetail' categorias.id %}"><h2>{{categorias.nome}}</h2></a>

            <p>{{categorias.descri}}</p>

            <p>----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</p>

    {% endfor %}

</div>
{% endblock content %}

times/templates/times/categoriesdetail.html
{% extends 'base.html' %}

{% load static %}


{% block content %}
<div class = 'branco'>
<h2>{{categorias.nome | safe}}</h2>
<p>{{categorias.descri | safe}}</p>
            {% for post in category.posts.all %}

                <a href="{% url 'times:detail' post.id %}"><img src="{{ post.image_url }}"
                        alt="Imagem do Post {{ post.nome}}" width="500" height="250"></a>
                <p><h2>{{ post.nome | safe}}</h2></p>
                <p><b><i>{{ post.data | safe}}</i></b></p>

                <p>----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</p>
            {% endfor %}

</div>
{% endblock content %}

times/templates/times/comment.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
<div class = 'branco'>
<h2>Comentar na publicação {{ post.name }} </h2>

<form action="{% url 'times:comment' post.id %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Postar comentario</button>
</form>

<p><a href="{% url 'times:detail' post.id %}">Voltar</a></p>
</div>
{% endblock content %}

times/templates/times/create.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
<div class = 'p2'>
    Inserir Novo post
</div>
<form method="POST" action="{% url 'times:create' %}">
    {% csrf_token %}
    <div class = 'branco'>
        {{ form.as_p }}
    <button type="submit">Criar</button>
</div>
</form>

{% endblock content %}

times/templates/times/delete.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
<div class = 'branco'>
<form action="{% url 'times:delete' post.id  %}" method="post">
    {% csrf_token %}
    <p>
        Você tem certeza que deseja apagar a publicação "{{ post.nome }} ({{ post.data }})"?
    </p>
    <button type="submit">Apagar</button>
</form>
</div>
{% endblock content %}

times/templates/times/detail.html
{% extends 'base.html' %}

{% load static %}

{% block title %}
{{ post.nome }} ({{ post.data }}
{% endblock title %}

{% block content %}
<h2>
 Detalhes do post {{ post.nome }} ({{ post.data }})
</h2>
    <div class = 'branco'>
    <img src="{{ post.image_url }}" alt="Imagem do Post {{ post.nome}}">

        <h3>Nome:</h3> {{ post.nome }}
        <h3>Ano de Publicação:</h3> {{ post.data }} 
        <h3>Conteudo</h3> {{ post.text }} 
        {% if post.categorias_set.all %}

        <h2></h2><b>Categorias:</b> <i> {{ post.categorias_set.all|join:", " }} </i>

        {% endif %}

        <p>----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</p>
        <h3><a href="{% url 'times:update' post.id  %}">Editar</a></h3>
        <h3><a href="{% url 'times:delete' post.id  %}">Apagar</a></h3>

        <p>----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</p>
                <h2>Comentarios</h2>

                {% if post.comentarios_set.all %}
                    {% for comentarios in post.comentarios_set.all|dictsortreversed:"data" %}
                        
                                "{{ comentarios.text | safe }}"
                            
                                     <b> — {{ comentarios.author | safe }} </b> - <i> {{ comentarios.data | date }} </i>
 
                        <p>---------------------------------------------------------------------------------------</p>
                    {% endfor %}
                {% else %}
                    <p>Ainda não existem comentarios sobre essa publicação.</p>
                {% endif %}
        
            <a href="{% url 'times:comment' post.id %}"><button>Comentar</button></a>
            <p>----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</p>
        </section>
        
</div>


{% endblock content %}

times/templates/times/index.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
<div class = 'p2'>
Todas as publicações
</div>
<div class = 'branco'>
    <p><h3>Muitos resultados?</h3> <a href="{% url 'times:search' %}">Buscar publicações</a></p>

    <p>----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</p>

{% if list_post %}

    {% for post in list_post %}
    <div class = 'principal'>
        <a href="{% url 'times:detail' post.id  %}"><img src="{{ post.image_url }}"
            alt="Imagem do post {{post.nome}}" width="500" height="250"></a>
            <h3> {{ post.nome }}</h3>({{ post.data }})

    </div>
    <p>----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</p>
    {% endfor %}

{% else %}
<p>Não foi encontrado nenhuma publicação.</p>
</div>
{% endif %}

{% endblock content %}

times/templates/times/search.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
<div class = 'p2'>
Busca de publicações por nome
</div>
<form action="{% url 'times:search' %}">
    <div class = 'branco'>
    <p>
        <label for="id_query">Título:</label>
        <input type="text" name="query" id="id_query" />
    </p>
    <button type="submit">Buscar</button>
</div>
</form>


<div class = 'branco'>
    <h2>
        Resultado da Busca
    </h2>
{% if list_post %}
<section class="lista-de-cards">
    {% for post in list_post %}
    <article class="card">
        <img src="{{ post.image_url }}" alt="Imagem do Post {{ post.nome}}">
        <p>{{ post.nome }} ({{ post.data }})</p>
    </article>
    {% endfor %}
</section>
{% else %}
<p>Não foi encontrado nenhuma publicação para a busca.</p>
{% endif %}
</div>
{% endblock content %}

times/templates/times/update.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
<h2>Atualizar dados da publicação {{ post.nome }} ({{ post.data}})</h2>
<form method="POST" action="{% url 'times:update' post.id %}">
    {% csrf_token %}
    <div class = 'branco'>
        {{ form.as_p }}
        <button type="submit">Atualizar</button>
    </div>
</form>

{% endblock content %}